version: '3.3'

services:
  flox:
    build: .
    restart: always
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flox'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'flox'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'test'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
